### ISSUE TITLE
TypeErrors when DEBUG_TERMINAL = True

### ISSUE THREAD

**Issue by Dimi20cen** [163gal/Lemonade#13]
When I run the activity with `DEBUG_TERMINAL = True` in the activity.py, I get the following two tracebacks

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/_propertyhelper.py", line 401, in obj_set_property
    prop.fset(self, value)
  File "/usr/local/lib/python3.10/dist-packages/sugar3/graphics/toolbarbox.py", line 188, in set_padding
    self._toolbar_alignment.set_padding(0, 0, pad, pad)
TypeError: Must be number, not VteActivity
```

```
Traceback (most recent call last):
  File "/usr/local/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activityinstance.py", line 231, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/local/lib/python3.10/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
  File "/home/dim/Documents/GitHub/Lemonade/activity.py", line 53, in __init__
    self._vte.set_colors(Gdk.color_parse('#E7E7E7'),
TypeError: argument foreground: Expected Gdk.RGBA, but got gi.overrides.Gdk.Color
```

**Comment by chimosky** [comment]
For future references, don't include GH issue numbers in your commit message as git doesn't understand that.

**Comment by Dimi20cen** [comment]
I'm sorry I don't understand what you mean. Is there a problem with how this issue is created, or is it about a commit message I've made?

**Comment by quozl** [comment]
The commit message.  By referencing an issue inside a commit message, which GitHub loves because it uses their services, you create a dependency on GitHub for when the commit message is re-read in future by someone trying to find and fix a fault, or using git bisect.  Explain the problem instead.  We keep the git repository, we don't keep the GitHub issues or pull requests.

**Comment by Dimi20cen** [comment]
Ahhh yeah, that was an oversight. Github desktop might have suggested it and I accidentally pressed on it
